name: alpine cuckoo

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      -
        name: Build alpine cuckoo rootfs
        run: |
          ./rootfs-generator.sh linux/amd64 alpine
      -
        name: Upload archive
        uses: actions/upload-artifact@v2
        with: 
          name: alpine amd64
          path: alpine_linux_amd64.tar.gz
