name: build

on:
  workflow_dispatch:

permissions:
  contents: write

env:
  GOOS: linux
  GOARCH: arm
  GOARM: arm64
  
jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      -
        name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      -
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          distribution: goreleaser
          version: latest
          args: build --single-target --snapshot
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      -
        name: find files
        run: |
          find dist
      -
        name: Upload archive
        uses: actions/upload-artifact@v2
        with: 
          name: cuckoo arm64
          path: dist/cuckoo_linux_arm64/cuckoo
