name: build

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      -
        name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      -
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          distribution: goreleaser
          version: latest
          args: build --single-target --snapshot
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Run built program
        run: |
          #./rootfs-generator.sh linux/amd64 nodered/node-red
          #mkdir nodered
          #sudo tar zxf nodered_node-red_linux_amd64.tar.gz -C nodered
          #sudo dist/cuckoo_linux_amd64_v1/cuckoo run nodered
          ./rootfs-generator.sh linux/amd64 alpine
          ls -l
          mkdir alpine
          sudo tar zxf alpine_linux_amd64.tar.gz -C alpine
          sudo echo "" > alpine/.cuckoo/cmd
          sudo dist/cuckoo_linux_amd64_v1/cuckoo alpine "cat /proc/self/cmdline"
          sudo dist/cuckoo_linux_amd64_v1/cuckoo alpine mount
          sudo dist/cuckoo_linux_amd64_v1/cuckoo alpine df
          sudo dist/cuckoo_linux_amd64_v1/cuckoo alpine ps
          sudo dist/cuckoo_linux_amd64_v1/cuckoo alpine "ls -l"
          sudo dist/cuckoo_linux_amd64_v1/cuckoo alpine "ls /proc"
          sudo dist/cuckoo_linux_amd64_v1/cuckoo alpine "ip link"
          sudo dist/cuckoo_linux_amd64_v1/cuckoo alpine "ip addr"
          sudo dist/cuckoo_linux_amd64_v1/cuckoo alpine "apk update"
          sudo dist/cuckoo_linux_amd64_v1/cuckoo alpine "apk add nano tcpdump"
