name: build

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      -
        name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      -
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          distribution: goreleaser
          version: latest
          args: build --single-target --snapshot
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Run built program
        run: |
          #./rootfs-generator.sh linux/amd64 nodered/node-red
          ./rootfs-generator.sh linux/amd64 alpine
          ls -l
          mkdir rootfs
          cd rootfs
          tar zxf ../alpine_linux_amd64.tar.gz
          cat .cuckoo/*
          sudo ../dist/cuckoo_linux_amd64/cuckoo run /bin/sh -c "pwd"
          sudo ../dist/cuckoo_linux_amd64/cuckoo run /bin/sh -c "ls -l"
          #sudo ../dist/cuckoo_linux_amd64/cuckoo run /bin/sh -c "ls /proc"
          #sudo ../dist/cuckoo_linux_amd64/cuckoo run /bin/sh -c "ps"
          #sudo ../dist/cuckoo_linux_amd64/cuckoo run /bin/sh -c "apk update"
          

