name: foobar cuckoo

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      -
        name: Build foobar cuckoo rootfs
        run: |
          ./rootfs-generator.sh linux/arm64 runcitadel/deno:main-arm64
      -
        name: Upload archive
        uses: actions/upload-artifact@v2
        with: 
          name: foobar arm64
          path: foobar_linux_arm64.tar.gz
