name: mqtt-explorer cuckoo

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      -
        name: Build mqtt-explorer cuckoo rootfs
        run: |
          ./rootfs-generator.sh linux/arm64 emqx/mqttx-web
      -
        name: Upload archive
        uses: actions/upload-artifact@v2
        with: 
          name: mqtt-explorer arm64
          path: emqx_mqttx-web_linux_arm64.tar.gz
