name: nodered cuckoo amd64

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      -
        name: Build nodered cuckoo rootfs
        run: |
          ./rootfs-generator.sh linux/amd64 nodered/node-red
      -
        name: Upload archive
        uses: actions/upload-artifact@v2
        with: 
          name: nodered amd64
          path: nodered_node-red_linux_amd64.tar.gz
